### ISSUE TITLE
Include LICENSE file in this repository, too

### ISSUE THREAD

**Issue by TC01** [milochristiansen/axis2#1]
Same as [the issue I filed on the lua repository](https://github.com/milochristiansen/lua/issues/5), would it be possible for you to add a LICENSE file to this repository too explicitly stating the zlib license of the code?

Fedora [packaging guidelines](https://fedoraproject.org/wiki/Packaging:LicensingGuidelines#License_Text) require packagers to contact upstream asking for a LICENSE file to be included when one isn't present (even though the files do all have license headers as is the case here). 

I was asked to do this in the [review for this package](https://bugzilla.redhat.com/show_bug.cgi?id=1411961).

Thanks in advance!

**Comment by milochristiansen** [comment]
Sure, no problem!

I should have done it when I added one for the Lua repository, but I forgot...

Anyway, it has one now.
